#!/bin/sh
# Find latest tag from GitHub (tags are like v3.3.0)
# Requires: curl, sed, head
curl -fsSL "https://github.com/edrlab/thorium-reader/tags" \
  | sed -n 's/.*\/edrlab\/thorium-reader\/releases\/tag\/v\([0-9][0-9.]*\)".*/\1/p' \
  | head -n 1

